<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MyApp.Api.UnitTests</RootNamespace>
    <AssemblyName>MyApp.Api.UnitTests</AssemblyName>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Example\Domain\MyApp.Modules.Example.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Example\Application\MyApp.Modules.Example.Application.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\MyApp.BuildingBlocks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
