// Rebrand the scaffold: replace the template identity with your own, everywhere.
//
// Usage: node scripts/rename.mjs <NewPascalName>      (e.g. AcmeShop)
//
// The scaffold's identity is two derived tokens:
//   MyApp   (PascalCase) -> <NewPascalName>   — .NET namespaces, assemblies, project files
//   my-app  (kebab-case) -> <new-kebab>        — npm scope/names, image tags, docs
// This script rewrites those tokens in every text file and renames any file whose
// name contains "MyApp" (the .csproj files). Afterwards, run `pnpm install` to refresh
// the lockfile and `pnpm run verify` to confirm everything is green.
import { readdirSync, readFileSync, writeFileSync, renameSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

const OLD_PASCAL = "MyApp";
const OLD_KEBAB = "my-app";

const [, , rawName] = process.argv;
if (!rawName || !/^[A-Z][A-Za-z0-9]+$/.test(rawName)) {
  console.error("Usage: node scripts/rename.mjs <NewPascalName>   (e.g. AcmeShop)");
  process.exit(2);
}

const newPascal = rawName;
const newKebab = rawName.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

// Do not descend into generated or vendored trees, and never rewrite the scripts
// whose OLD_* / template-name constants must survive the rebrand — this one, and
// init.mjs with the test that asserts against those constants — or the lockfile
// (regenerated by pnpm install).
const ignoreDirs = new Set([".git", "node_modules", "bin", "obj", "dist", ".vite", ".cache", ".context"]);
const ignoreFiles = new Set(["pnpm-lock.yaml", "rename.mjs", "init.mjs", "init.test.mjs"]);
const textNames = new Set(["Dockerfile", ".gitignore", ".dockerignore", ".gitattributes", ".env.example"]);
const textExtensions = new Set([
  ".cs", ".csproj", ".props", ".slnx", ".sln", ".json", ".mjs", ".js", ".cjs",
  ".ts", ".tsx", ".md", ".yml", ".yaml", ".html", ".css", ".config", ".example",
]);

function isTextFile(name) {
  if (textNames.has(name)) return true;
  const dot = name.lastIndexOf(".");
  return dot >= 0 && textExtensions.has(name.slice(dot));
}

function rewrite(text) {
  return text.split(OLD_PASCAL).join(newPascal).split(OLD_KEBAB).join(newKebab);
}

let edited = 0;
let renamed = 0;

function walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);

    if (entry.isDirectory()) {
      if (!ignoreDirs.has(entry.name)) {
        walk(path);
      }
      continue;
    }

    if (!entry.isFile() || ignoreFiles.has(entry.name)) {
      continue;
    }

    if (isTextFile(entry.name)) {
      const original = readFileSync(path, "utf8");
      const updated = rewrite(original);
      if (updated !== original) {
        writeFileSync(path, updated);
        edited++;
      }
    }

    if (entry.name.includes(OLD_PASCAL)) {
      renameSync(path, join(dir, entry.name.split(OLD_PASCAL).join(newPascal)));
      renamed++;
    }
  }
}

walk(repoRoot);

console.log(`Rebranded ${OLD_PASCAL}/${OLD_KEBAB} -> ${newPascal}/${newKebab}`);
console.log(`  files edited:  ${edited}`);
console.log(`  files renamed: ${renamed}`);
console.log("Next: run `pnpm install`, then `pnpm run verify`.");
